// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SurfThePagesTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void surfThePages() {
    driver.get("http://127.0.0.1:8282/info");
    driver.manage().window().setSize(new Dimension(919, 695));
    driver.findElement(By.cssSelector(".u-button-style use")).click();
    driver.findElement(By.linkText("About")).click();
    driver.findElement(By.cssSelector("svg:nth-child(1)")).click();
    driver.findElement(By.linkText("Contact")).click();
    driver.findElement(By.cssSelector(".u-button-style use")).click();
    driver.findElement(By.linkText("Home")).click();
    driver.findElement(By.cssSelector(".u-button-style > svg:nth-child(1)")).click();
    driver.findElement(By.linkText("About")).click();
  }
}
